---
name: Security check - Bandit

on: push  # yamllint disable-line rule:truthy

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Bandit security check for code
        uses: akaihola/bandit-report-artifacts@use-config
        with:
          project_path: .
          config_file: ./.bandit.code.yaml

      - name: Bandit security check for tests
        uses: akaihola/bandit-report-artifacts@use-config
        with:
          project_path: ./src/darker/tests
          config_file: ./.bandit.tests.yaml

      - name: Bandit security check for GitHub Action `main.py` tests
        uses: akaihola/bandit-report-artifacts@use-config
        with:
          project_path: ./action/tests
          config_file: ./.bandit.tests.yaml
