---
name: isort

on: push  # yamllint disable-line rule:truthy

jobs:
  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install 'isort>=5.0.1'
      - uses: Gobot1234/lint-action@v.1.8.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          isort: true
          continue_on_error: false
